name: Release tags

on:
  push:
    tags:
      - 0.*
      - 1.*
      - 2.*
      - 3.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
        name: Validate gradle wrapper
      - uses: actions/cache@v1
        name: Cache gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Configure Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: test and build
        run: ./gradlew build publish githubRelease
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}